### ISSUE TITLE
Add profiling information to CI

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zbc-go#120]
example: 

```go test -cpuprofile cpu.prof -memprofile mem.prof -race -trace trace.out -covermode=atomic tests/test-task-subscriptions/task_subscriptions_multiplepartitions_test.go -v```

will produce following files:
 * mem.prof
 * cpu.prof
 * trace.out

**Comment by menski** [comment]
maybe add a environment variable to the Makefile to specify arbitrary opts for go invocation. We can then set the required parameters in the Jenkins job and archive the outputs.

@jsam could you prepare the Makefile change? I can do the Jenkins part.
