### ISSUE TITLE
[cmd]: when I do not provide a config file, defaults are used

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/zbc-go#27]
Just an idea, not sure whether it is a good one:

Assume I am using the `zbctl` tool and I do not provide a config file, then currently I get the following error:

```
2017/08/09 20:57:48 Reading configuration failed. Expecting to found configuration file at /etc/zeebe/config.toml
2017/08/09 20:57:48 HINT: Configuration file is not in place. Try setting configuration path with:
2017/08/09 20:57:48  zbctl --config <path to config.toml>
```

An idea would be that in that case we do not get an error but the tool by default connects to the local broker at 127.0.0.1:51015

**Comment by jsam** [comment]
Implemented in #9d62270ab38612fc504f4e0bb869add04d8ece2e
