### ISSUE TITLE
Task/Topic Subscriptions subscribe to all partitions of a topic

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zbc-go#48]
If a Task/Topic subscription is opened on a topic the client does the following steps to subscribe to all partitions:
1. request partition ids from system-topic (partition id: 0) https://github.com/zeebe-io/zeebe/issues/530
1. get current leader for all partitions from topology request
1. create a subscription for every partition against the current leader
1. send the events from all subscriptions to the subscription channel which is returned to the user

Possible failure scenarios:
- Scenario: during opening the subscription on a suspected leader of a partition an partition not found error is returned
  - Reason: the broker is not leader of the partition anymore
  - Solution: refresh topology and retry opening the subscription with new leader
- Scenario: during opening the subscription on a leader the subscription is rejected
  - Reason: there is already a subscription for this subscription name opened
  - Solution: abort the subscription process and close all already established subscriptions to other partitions
- Scenario: a subscription channel is closed
  - Reason: a network layer event occurred which closed the socket connection 
  - Solution: Reconnect to broker by opening a new connection and subscription
- Scenario: a subscription is closed by the broker
  - Reason: the broker lost leadership of the partition
  - Solution: update topology to get the new leader and create a new subscription to the partition on the new leader

**Comment by jsam** [comment]
related: #40

**Comment by menski** [comment]
for reference the write up of our meeting: https://github.com/zeebe-io/zeebe/issues/142#issuecomment-345744408
