### ISSUE TITLE
CLI: Closing subscription hangs when broker is closed

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zbc-go#57]
Steps to reproduce:

* start broker
* open task subscription
* stop broker
* close subscription

The last step hangs after printing `Closing subscription`

**Comment by jsam** [comment]
I tried to reproduce this on master but I cannot.

The default timeout period is 5 seconds. After 5 seconds it should print 

```failed to close subscription:  Message retry deadline reached```
