### ISSUE TITLE
Create ConnectionHandler 

### ISSUE THREAD

**Issue by jsam** [zeebe-io/zbc-go#76]
1) Handle multiple connections
2) Handle error handling for multiple connections
  * Client should distinguish expected errors from unexpected ones (sync with Thorben) 
3) Handle keep alive messages for multiple connections

**Comment by menski** [comment]
Keep Alive Control Message Type:
https://github.com/zeebe-io/zb-transport/blob/5e45b3e37ee01857f508f7b20e209a9c1fdcab6b/src/main/java/io/zeebe/transport/impl/ControlMessages.java#L31
