### ISSUE TITLE
Support unique partition ids

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zbc-go#81]
General: Wherever we previously transmitted both, topic name and partition id, we now only need to send the partition id.

Changes on SBE level (see https://github.com/zeebe-io/zb-protocol/commit/a14918a5adfb59bd1769c2ff3a62d091b9631ddb#diff-aa3cfd0b2c72db625cc18431127e4ab4):

* `ExecuteCommandResponse`, `ExecuteCommandRequest`, `SubscribedEvent`:
  * **After**: `topicName` field is gone
* `ControlMessageRequest`:
  * **Before**: For requests that address a partition, the partition id was sent as part of the serialzied `data` field (=> task subscriptions)
  * **After**: I added an optional `partitionId` field to the SBE message. This needs only be set when a specific partition is addressed. It is no longer required to send the partition id as part of the `data` field.
  * This protocol change is not strictly required. It made some things easier for me in the Java client. If it makes it worse in go client, we can reverse it.

Changes on control message request level (i.e. msgpack-encoded control message request body):

* Close topic subscription:
  * `topicName` and `partitionId` field removed
* Increase task subscription credits:
  * `topicName` and `partitionId` removed
* Create task subscription
  * `topicName` and `partitionId` removed
* Close task subscription:
  * `topicName` and `partitionId` field removed

**Comment by menski** [comment]
I think `topicName` and `partitionId` was removed from close task/topic subscription not only `partitionId`. Can you confirm that @ThorbenLindhauer?

**Comment by ThorbenLindhauer** [comment]
Yes, correct.

**Comment by menski** [comment]
thanks I updated the description

**Comment by menski** [comment]
implemented with #95
